In [2]:
import pandas as pd
import numpy as np
train = pd.read_csv("train.csv")
train

Loan_ID  Gender Married Dependents     Education Self_Employed  \
0    LP001002    Male      No          0      Graduate            No   
1    LP001003    Male     Yes          1      Graduate            No   
2    LP001005    Male     Yes          0      Graduate           Yes   
3    LP001006    Male     Yes          0  Not Graduate            No   
4    LP001008    Male      No          0      Graduate            No   
..        ...     ...     ...        ...           ...           ...   
609  LP002978  Female      No          0      Graduate            No   
610  LP002979    Male     Yes         3+      Graduate            No   
611  LP002983    Male     Yes          1      Graduate            No   
612  LP002984    Male     Yes          2      Graduate            No   
613  LP002990  Female      No          0      Graduate           Yes   

     ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0         NaN             360.0   
1               4583             1508.0       128.0             360.0   
2               3000                0.0        66.0             360.0   
3               2583             2358.0       120.0             360.0   
4               6000                0.0       141.0             360.0   
..               ...                ...         ...               ...   
609             2900                0.0        71.0             360.0   
610             4106                0.0        40.0             180.0   
611             8072              240.0       253.0             360.0   
612             7583                0.0       187.0             360.0   
613             4583                0.0       133.0             360.0   

     Credit_History Property_Area Loan_Status  
0               1.0         Urban           Y  
1               1.0         Rural           N  
2               1.0         Urban           Y  
3               1.0         Urban           Y  
4               1.0         Urban           Y  
..              ...           ...         ...  
609             1.0         Rural           Y  
610             1.0         Rural           Y  
611             1.0         Urban           Y  
612             1.0         Urban           Y  
613             0.0     Semiurban           N  

[614 rows x 13 columns]

In [3]:
train.describe()

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
count       614.000000         614.000000  592.000000         600.00000   
mean       5403.459283        1621.245798  146.412162         342.00000   
std        6109.041673        2926.248369   85.587325          65.12041   
min         150.000000           0.000000    9.000000          12.00000   
25%        2877.500000           0.000000  100.000000         360.00000   
50%        3812.500000        1188.500000  128.000000         360.00000   
75%        5795.000000        2297.250000  168.000000         360.00000   
max       81000.000000       41667.000000  700.000000         480.00000   

       Credit_History  
count      564.000000  
mean         0.842199  
std          0.364878  
min          0.000000  
25%          1.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [4]:
train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [5]:
train.fillna(train.mean(), inplace=True)
train.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount            0
Loan_Amount_Term      0
Credit_History        0
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
train.fillna(train.Gender.mode()[0], inplace=True)
train.fillna(train.Married.mode()[0], inplace=True)
train.fillna(train.Dependents.mode()[0], inplace=True)
train.fillna(train.Self_Employed.mode()[0], inplace=True)
train.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [7]:
# split data
X = train.drop("Loan_Status", axis=1)
y = train["Loan_Status"]

In [8]:
train.Loan_Amount_Term = np.log(train.Loan_Amount_Term)

In [9]:
y

0      Y
1      N
2      Y
3      Y
4      Y
      ..
609    Y
610    Y
611    Y
612    Y
613    N
Name: Loan_Status, Length: 614, dtype: object

In [10]:
X = pd.get_dummies(X)
train = pd.get_dummies(train)
X

ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0               5849                0.0  146.412162             360.0   
1               4583             1508.0  128.000000             360.0   
2               3000                0.0   66.000000             360.0   
3               2583             2358.0  120.000000             360.0   
4               6000                0.0  141.000000             360.0   
..               ...                ...         ...               ...   
609             2900                0.0   71.000000             360.0   
610             4106                0.0   40.000000             180.0   
611             8072              240.0  253.000000             360.0   
612             7583                0.0  187.000000             360.0   
613             4583                0.0  133.000000             360.0   

     Credit_History  Loan_ID_LP001002  Loan_ID_LP001003  Loan_ID_LP001005  \
0               1.0                 1                 0                 0   
1               1.0                 0                 1                 0   
2               1.0                 0                 0                 1   
3               1.0                 0                 0                 0   
4               1.0                 0                 0                 0   
..              ...               ...               ...               ...   
609             1.0                 0                 0                 0   
610             1.0                 0                 0                 0   
611             1.0                 0                 0                 0   
612             1.0                 0                 0                 0   
613             0.0                 0                 0                 0   

     Loan_ID_LP001006  Loan_ID_LP001008  ...  Dependents_3+  Dependents_Male  \
0                   0                 0  ...              0                0   
1                   0                 0  ...              0                0   
2                   0                 0  ...              0                0   
3                   1                 0  ...              0                0   
4                   0                 1  ...              0                0   
..                ...               ...  ...            ...              ...   
609                 0                 0  ...              0                0   
610                 0                 0  ...              1                0   
611                 0                 0  ...              0                0   
612                 0                 0  ...              0                0   
613                 0                 0  ...              0                0   

     Education_Graduate  Education_Not Graduate  Self_Employed_Male  \
0                     1                       0                   0   
1                     1                       0                   0   
2                     1                       0                   0   
3                     0                       1                   0   
4                     1                       0                   0   
..                  ...                     ...                 ...   
609                   1                       0                   0   
610                   1                       0                   0   
611                   1                       0                   0   
612                   1                       0                   0   
613                   1                       0                   0   

     Self_Employed_No  Self_Employed_Yes  Property_Area_Rural  \
0                   1                  0                    0   
1                   1                  0                    1   
2                   0                  1                    0   
3                   1                  0                    0   
4                   1                  0                    0   

In [11]:
y.head()

0    Y
1    N
2    Y
3    Y
4    Y
Name: Loan_Status, dtype: object

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

A. Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import confusion_matrix

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Matrix:", metrics.confusion_matrix(y_test, y_pred))

Accuracy: 0.8292682926829268
Matrix: [[12 20]
 [ 1 90]]


B. Decision Tree

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_pred1 = model.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
matrix1 = confusion_matrix(y_test, y_pred)
matrix1

Accuracy: 0.8292682926829268


array([[12, 20],
       [ 1, 90]], dtype=int64)

C. Random Forest

In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)
y_pred2 = model.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
matrix2 = confusion_matrix(y_test, y_pred)
matrix2

Accuracy: 0.8292682926829268


array([[12, 20],
       [ 1, 90]], dtype=int64)

D. Support Vector Machine

In [16]:
from sklearn.svm import SVC

svm_model = SVC()
svm_model.fit(X_train, y_train)
y_pred3 = model.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
matrix3 = confusion_matrix(y_test, y_pred)
matrix3

Accuracy: 0.8292682926829268


array([[12, 20],
       [ 1, 90]], dtype=int64)

E. Naive Bayes

In [17]:
from sklearn.naive_bayes import GaussianNB

nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred4 = model.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
matrix4 = confusion_matrix(y_test, y_pred)
matrix4

Accuracy: 0.8292682926829268


array([[12, 20],
       [ 1, 90]], dtype=int64)

F. K-Nearest Neighbor (KNN)

In [18]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred5 = knn.predict(X_test)
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
matrix5 = confusion_matrix(y_test, y_pred)
matrix5

Accuracy: 0.8292682926829268


array([[12, 20],
       [ 1, 90]], dtype=int64)

In [19]:
# write the result in csv file

predictions = pd.DataFrame(y_pred2, columns=["predictions"].to_csv("H8_NB_Credit_Predictions.csv"))

AttributeError: 'list' object has no attribute 'to_csv'