In [1]:
import numpy as np

In [6]:
myArray = np.array([1,2,3,4,5])
myList = [1,2,3,4,5,6]

In [7]:
myArray

array([1, 2, 3, 4, 5])

In [15]:
myList

[1, 2, 3, 4, 5, 6]

In [21]:
#perkalian
multiplyList = myList * 5
multiplyArray = myArray * 5

print(multiplyList, multiplyArray)

[1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6] [ 5 10 15 20 25]


In [14]:
myNewArray = np.array(myList)

In [ ]:
myNewArray * 5

In [19]:
#pembagian list tidak bisa dibagi
devideList = myList / 2
print(devideList)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [23]:
#penjumlahan
myArray = np.array([1,2,3,4,5])
#operasi satu bilangan
addMyArray = myArray + 2
reduceMyArray = myArray - 2
square = myArray **2

print("add: ", addMyArray)
print("reduce: ", reduceMyArray)
print("square: ", square)

add:  [3 4 5 6 7]
reduce:  [-1  0  1  2  3]
square:  [ 1  4  9 16 25]


In [26]:
#boolean operation

myArray = np.array([1,2,3,4,5])
isMyarrayMoreThan3 = myArray > 3

In [27]:
isMyarrayMoreThan3

array([False, False, False,  True,  True])

In [28]:
#Filtering

valueMoreThan3c = myArray[myArray > 3]
print(valueMoreThan3c)

[4 5]


In [34]:
#array 2 dimensi dengan ukuran 3 x 4

array2D = np.array([[1,2,3,4],
                    [4,5,6,7],
                    [8,9,10,11]
                   ])


In [35]:
# melihat ukuran array

print(array2D.shape)


(3, 4)


In [36]:
# melihat type data

print(type(array2D))

<class 'numpy.ndarray'>


In [38]:
# mengambil dari array 2D angka 4, indeks 0

print(array2D[1,0])

# dengan cara lain
print(array2D[1][0])

4
4


In [45]:
# rentang array 1:2 2:3

print(array2D[1:, 1:])

[[ 5  6  7]
 [ 9 10 11]]


In [48]:
print(array2D[0:2,1:2])

[[2]
 [5]]


In [49]:
print(array2D[0:][1:3])

[[ 4  5  6  7]
 [ 8  9 10 11]]


In [58]:
print(array2D[:, 1:3])

[[ 2  3]
 [ 5  6]
 [ 9 10]]


In [33]:

array2D = np.array([[1,2,3,4],
                    [4,5,6,7],
                    [8,9,10,11]
                   ])

print(array2D[0:2, 1:3 ])

[[2 3]
 [5 6]]


In [5]:
# import data from csv
import numpy as np

In [6]:
myStudentData = np.genfromtxt('./data.csv', skip_header=1, delimiter=",", filling_values=40)
myStudentData

array([[70., 75., 80., 30.],
       [75., 80., 90., 68.],
       [65., 77., 60., 90.],
       [40., 60., 55., 75.]])

In [8]:
# Mencari isi nilai yang terbesar -> amax

maxInClass = np.amax(myStudentData, axis = 0)
print(maxInClass)


[75. 80. 90. 90.]


30.0

In [53]:
# Mencari isi nilai yang terkecil -> amin

minInClass = np.amin(myStudentData, axis=1)
print(minInClass)

[30. 68. 60. 40.]


In [58]:
# mencari rata-rata -> mean

rata2SiswaSetiapMatpel = np.mean(myStudentData, axis = 1)
print(rata2SiswaSetiapMatpel)

[63.75 78.25 73.   57.5 ]


In [94]:
# menambahkan data -> append dengan axis 1 menambahkan kolom, memerlukan kurung siku
# AXIS 0 menambahkan baris di bawah, tidak perlu kurung siku

myStudentData = np.append(myStudentData, [[65,70,40,90,65,70,40,90]], axis = 0)
myStudentData

array([[70., 75., 80., 30., 45., 45., 45., 65.],
       [75., 80., 90., 68., 50., 50., 50., 70.],
       [65., 77., 60., 90., 40., 40., 40., 40.],
       [40., 60., 55., 75., 90., 90., 90., 90.],
       [65., 70., 40., 90., 65., 70., 40., 90.]])

In [95]:
myStudentData

array([[70., 75., 80., 30., 45., 45., 45., 65.],
       [75., 80., 90., 68., 50., 50., 50., 70.],
       [65., 77., 60., 90., 40., 40., 40., 40.],
       [40., 60., 55., 75., 90., 90., 90., 90.],
       [65., 70., 40., 90., 65., 70., 40., 90.]])

In [98]:
np.lookfor("median")

Search results for 'median'
---------------------------
numpy.median
    Compute the median along the specified axis.
numpy.nanmedian
    Compute the median along the specified axis, while ignoring NaNs.
numpy.ma.median
    Compute the median along the specified axis.
numpy.pad
    Pad an array.
numpy.quantile
    Compute the q-th quantile of the data along the specified axis.
numpy.percentile
    Compute the q-th percentile of the data along the specified axis.
numpy.nanquantile
    Compute the qth quantile of the data along the specified axis,
numpy.nanpercentile
    Compute the qth percentile of the data along the specified axis,
numpy.random.Generator.logistic
    Draw samples from a logistic distribution.
numpy.random.RandomState.logistic
    Draw samples from a logistic distribution.
numpy.ma.tests.test_extras.TestMedian.test_docstring_examples
    test the examples given in the docstring of ma.median

In [99]:
[y, x] = myStudentData.shape

In [1]:
myStudentData[]

SyntaxError: invalid syntax (<ipython-input-1-b58b3e9b7f67>, line 1)

In [101]:
myStudentData

array([[70., 75., 80., 30., 45., 45., 45., 65.],
       [75., 80., 90., 68., 50., 50., 50., 70.],
       [65., 77., 60., 90., 40., 40., 40., 40.],
       [40., 60., 55., 75., 90., 90., 90., 90.],
       [65., 70., 40., 90., 65., 70., 40., 90.]])

In [104]:
myNewStudent = np.delete(myStudentData, [7], axis = 1)
myNewStudent

array([[70., 75., 80., 30., 45., 45., 45.],
       [75., 80., 90., 68., 50., 50., 50.],
       [65., 77., 60., 90., 40., 40., 40.],
       [40., 60., 55., 75., 90., 90., 90.],
       [65., 70., 40., 90., 65., 70., 40.]])