In [ ]:
# jalankan proses one-hot encoding dengan pd.get_dummies()
#data = pd.get_dummies(data)

In [3]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import matplotlib.pyplot as plt

In [14]:
x = np.arange(10).reshape(-1,1)
y = np.array([0,0,0,0,0,0,1,1,1,1])

In [15]:
x

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [23]:
model = LogisticRegression(solver="liblinear", random_state=0)

In [24]:
model.fit(x, y)

LogisticRegression(random_state=0, solver='liblinear')

In [25]:
model.classes_

array([0, 1])

In [26]:
print(model.intercept_, model.coef_)

[-1.29366358] [[0.31888524]]


In [27]:
model.predict_proba(x)

array([[0.78476664, 0.21523336],
       [0.7260709 , 0.2739291 ],
       [0.65833723, 0.34166277],
       [0.58346351, 0.41653649],
       [0.50453053, 0.49546947],
       [0.42537106, 0.57462894],
       [0.34986154, 0.65013846],
       [0.28119674, 0.71880326],
       [0.22141863, 0.77858137],
       [0.17131962, 0.82868038]])

In [28]:
model.predict(x)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1])

In [29]:
model.score(x, y)

0.9

In [30]:
confusion_mat = confusion_matrix(y, model.predict(x))

In [31]:
confusion_mat

array([[5, 1],
       [0, 4]], dtype=int64)

In [32]:
model2 = LogisticRegression(solver="liblinear", random_state=0, max_iter=500, C=9.0)

In [33]:
model2.fit(x, y)
model2.score(x, y)

1.0

# Logistic Regression in Python: Handwriting Recognition

In [34]:
import matplotlib.pyplot as plt
import numpy as np

from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split #untuk membagi data menjadi train dan test set
from sklearn.preprocessing import StandardScaler #untuk melakukan normalisasi data, #untuk uji akurasi model -> model.score()
#melatih model dengan fungsi fit
#fungsi fit digunakan untuk menghitung rata2 dan deviasi standard
#dari setiap kolom atribut yg nntinya dipakai di fungsi transform

#train_test_split berfungsi untuk membagi array x dan y ke dalam 20% data testing(test_size=0.2)

#random_state bertujuan untuk dapat memastikan bahwa hasil pembagian dataset konsisten dan memberikan data yang sama setiap kali model dijalankan.
#Jika tidak ditentukan, maka tiap kali melakukan split, kita akan mendapatkan data train dan tes berbeda,yang juga akan membuat akurasi model ML menjadi berbeda tiap kali di-run.  

In [35]:
#get data

x, y = load_digits(return_X_y=True)

In [36]:
print(x)
print(y)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]
[0 1 2 ... 8 9 8]


In [37]:
#split data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)


In [38]:
#scale data
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train) #untuk mengaplikaksikan standard scaler pada data

In [39]:
#create a model and train it
model = LogisticRegression(solver="liblinear", C=0.05, multi_class="ovr", random_state=0)
model.fit(x_train, y_train)

LogisticRegression(C=0.05, multi_class='ovr', random_state=0,
                   solver='liblinear')

In [40]:
#Evaluate the model
x_test = scaler.transform(x_test)

In [41]:
y_pred = model.predict(x_test)

In [42]:
model.score(x_train, y_train)

0.964509394572025

In [43]:
#mendapatkan confusion matrix dengan confusion_matrix()

confusion_matrix(y_test, y_pred)

array([[27,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0, 32,  0,  0,  0,  0,  1,  0,  1,  1],
       [ 1,  1, 33,  1,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1, 28,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 29,  0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  0, 39,  0,  0,  0,  1],
       [ 0,  1,  0,  0,  0,  0, 43,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 39,  0,  0],
       [ 0,  2,  1,  2,  0,  0,  0,  1, 33,  0],
       [ 0,  0,  0,  1,  0,  1,  0,  2,  1, 36]], dtype=int64)

In [ ]:
cm = confusion_matrix(y_test, y_pred)
fig, ax = plt.subplots(figsize=(8,8))
ax.imshow(cm)
ax.grid(False)
ax.set_xlabel("Predicted outputs", color="black")
ax.set_ylabel("Actual outputs", color="black")

KNN algoritma 

In [44]:
weather = ["Sunny", "Sunny", "Overcast", "Rainy", "Rainy", "Rainy", "Overcast", 
           "Sunny", "Sunny", "Rainy", "Sunny", "Overcast", "Overcast", "Rainy"]

temp = ["Hot", "Hot", "Hot", "Mild", "Cool", "Cool", "Cool", "Mild", "Cool",
        "Mild", "Mild", "Mild", "Hot", "Mild"]

play = ["No", "No", "Yes", "Yes", "Yes", "No", 
        "Yes", "No", "Yes", "Yes", "Yes", "Yes", "Yes", "No"]

In [1]:
pwd

'C:\\Users\\resty\\Hacktiv8\\Class\\session_class\\Sesi_12'